### ISSUE TITLE
When querying for subclasses, put a where clause on content_type_id?

### ISSUE THREAD

**Issue by gavinwahl** [charettes/django-polymodels#21]
I have these models:

~~~python
class Base(PolymorphicModel):
    date = models.DateField()

    class Meta:
        unique_together = [
            ('content_type', 'date')
        ]

class Child1(Base):
    pass

class Child2(Base):
    pass
~~~

I did the query `Child1.objects.order_by('date')`, expecting that the index on (content_type_id, date) would be used. This is not the case, because the content_type_id is not filtered to Child1's content type (where clause + order by must be a prefix of the index for it to be used). The query `Child1.objects.filter(content_type=ContentType.objects.get_for_model(Child1)).order_by('date')` is much more efficient, because now the index can be used.

Is this something that polymodels could do automatically? I don't think it will negatively effect anything even if there's not an index that could be used.

**Comment by charettes** [comment]
I'm not sure this is something we want to do as it performs an unnecessary filter.

I just tried and it does affect performance on large tables (PostgreSQL).

Could you possibly create your unique index with `('data', 'content_type')` instead?

**Comment by gavinwahl** [comment]
> I just tried and it does affect performance on large tables (PostgreSQL).

For better or worse? For me it definitely makes it much better

> Could you possibly create your unique index with ('date', 'content_type') instead?

This seems semantically wrong - I want `SELECT * FROM base WHERE content_type_id = ? ORDER BY date`, which isn't able to use an index on date, content_type. In practice, it seems slower as well.

**Comment by charettes** [comment]
> For better or worse? For me it definitely makes it much better

It made it worse in my case.

`Child1.objects.order_by('date')` will always perform an INNER JOIN on the `base` table anyway so the filter by content type is redundant here.

If you want to perform a `SELECT * FROM base WHERE content_type_id = ? ORDER BY date` you can use the `select_subclasses` API:

```python
Base.objects.select_subclasses(Child1).order_by('date')
```

**Comment by charettes** [comment]
You can also use the `select_subclasses` API for the `Child1` case:

```python
Child1.object.select_subclasses(Child1).order_by('date')
```

**Comment by gavinwahl** [comment]
I'm just going to give the children a custom "PolymorphicFilterContentTypeManager" to always do the filtering for the models I'm interested in. It does seem icky to implicitly bake this filtering into django-polymodels itself.
