### ISSUE TITLE
select_subclasses() not available for multiple levels of abstractions

### ISSUE THREAD

**Issue by tehfink** [charettes/django-polymodels#24]
On Python 3.4 & Django 1.9:
```
class Item(PolymorphicModel, GenericAbstractBase):
  class Meta:
    abstract = True

class Subitem(Item):
  pass
```

Calling `Item.objects.select_subclasses()` gives:
```
AttributeError: Manager isn't available; Item is abstract
```

**Comment by charettes** [comment]
This has nothing to do with django-polymodels, the following should also fail:

```python
class Item(models.Model):
  class Meta:
    abstract = True

Item.objects
```

Please use Django's support channels to understand why managers aren't available on abstract models.

**Comment by tehfink** [comment]
Isn't PolymorphicModel an abstract model which nevertheless offers a manager?

**Comment by charettes** [comment]
As documented `PolymorphicModel` is an abstract model that offers a manager that will `inherited` by its first concrete subclass. See the `Animal` example in the README. From a quick look it seems like you'd want `Item` to be a concrete class here.

**Comment by tehfink** [comment]
Thanks for replying. Actually, I have about 3 more levels of abstract models (lots of real world variants resulting in shared code), and would like to avoid multi-table inheritance. After reading the Animal & Reptile examples, I had hoped to use django-polymodels to access the submodels of various abstract models at different levels in the inheritance tree.
