### ISSUE TITLE
field with text type does not have pk

### ISSUE THREAD

**Issue by freeman1981** [charettes/django-polymodels#26]
In[2]: from mutant.models import FieldDefinition
In[3]: FieldDefinition.objects.select_subclasses()
Out[3]: `[<MultiPointFieldDefinition: MultiPointFieldDefinition object>, <BigIntegerFieldDefinition: BigIntegerFieldDefinition object>, <FloatFieldDefinition: FloatFieldDefinition object>, <BooleanFieldDefinition: BooleanFieldDefinition object>, <TextFieldDefinition: TextFieldDefinition object>]`
In[4]: FieldDefinition.objects.select_subclasses()[0].pk
**No pk**
In[5]: FieldDefinition.objects.select_subclasses()[0]
Out[5]: `<TextFieldDefinition: TextFieldDefinition object>`
In[6]: FieldDefinition.objects.select_subclasses()[1].pk
**But here it is!**
Out[6]: 59
In[7]: FieldDefinition.objects.select_subclasses()[1]
Out[7]: `<BooleanFieldDefinition: BooleanFieldDefinition object>`

**Comment by charettes** [comment]
I cannot reproduce using the latest version of django-mutant and django-polymodels. Another thing the seems odd from your example is that `FieldDefinition.objects.select_subclasses()[0]` should be an instance of `MultiPointFieldDefinition`.
