### ISSUE TITLE
django error specifies a many-to-many relation through model 'login.Freelancer_groups', which has not been installed.

### ISSUE THREAD

**Issue by ashu12166** [charettes/django-polymodels#35]
I'm getting the following errors

> login.Freelancer.groups: (fields.E331) Field specifies a many-to-many relation through model 'login.Freelancer_groups', which has not been installed.
> login.Freelancer.user_permissions: (fields.E331) Field specifies a many-to-many relation through model 'login.Freelancer_user_permissions', which has not been installed.
> message_board.Post.author: (fields.E301) Field defines a relation with the model 'auth.User', which has been swapped out.
>         HINT: Update the relation to point at 'settings.AUTH_USER_MODEL'.

**Here is models.py** 

from django.contrib.auth.tests.custom_user import CustomUserManager
from django.db import models
from django.utils import timezone
from django.utils.http import urlquote
from django.utils.translation import ugettext_lazy as _
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager, PermissionsMixin
from crm import settings

class FreelancerManager(BaseUserManager):
    def create_user(self, name, skills, password=None):
        if not name:
            raise ValueError('Users must have a unique name ')

        user = self.model(
            name=self.name,
            skills=skills,
        )
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, name, skills, password):
        """
        Creates and saves a superuser with the given email, date of
        birth and password.
        """
        user = self.create_user(
            name,
            password=password,
            skills=skills,
        )
        user.is_admin = True
        user.save(using=self._db)
        return user

class Freelancer(AbstractBaseUser, PermissionsMixin):
    name = models.CharField(verbose_name='name',
                            max_length=20,
                            unique=True, )

    field_of_interest = models.CharField(max_length=200)
    skills = models.TextField()
    experience = models.TextField()

    is_active = models.BooleanField(default=True)
    is_admin = models.BooleanField(default=False)

    objects = FreelancerManager()

    USERNAME_FIELD = 'name'
    REQUIRED_FIELDS = ['skills']

    class Meta:
        db_table = 'auth_user'
        verbose_name = _('user')
        verbose_name_plural = _('users')

    def get_absolute_url(self):
        return "/users/%s/" % urlquote(self.name)

    def get_short_name(self):
        return self.name

    def get_full_name(self):
        return self.name

    def __str__(self):  # __unicode__ on Python 2
        return self.name

    def has_perm(self, perm, obj=None):
        # "Does the user have a specific permission?"
        # # Simplest possible answer: Yes, always
        return True

    def has_module_perms(self, applabel):
        # "Does the user have permissions to view the app `app_label`?"
        # Simplest possible answer: Yes, always
        return True

    @property
    def is_staff(self):
          return self.is_admin

**Comment by charettes** [comment]
From your report it doesn't look like it has something to do with this project. Please re-open if you can provide more details.
