### ISSUE TITLE
Incorrect migration behavior

### ISSUE THREAD

**Issue by Mogost** [charettes/django-polymodels#49]
Hi @charettes
It seems that `PolymorphicManager` of `django-polymodels` does not work in migrations.
https://github.com/charettes/django-polymodels/blob/07893e6d20ca7b104b5543b8ed5863afff06ff10/polymodels/managers.py#L83

I came across this when I create data migration and the code like following 
```python
MyProxyModel = apps.get_model('app', 'Model')
MyProxyModel.objects.all()
```
returned me all objects, without filtering on content type.

How I see there is `use_in_migrations` option for model managers [in Django](https://docs.djangoproject.com/en/3.0/topics/migrations/#model-managers).
Should that option be present in `PolymorphicManager`?

**Comment by charettes** [comment]
`.all()` is not meant to filter by subclasses but data migration support is effectively still lacking and is tracked in #34.
