### ISSUE TITLE
Explicitly state usage of MTI

### ISSUE THREAD

**Issue by thatguysimon** [charettes/django-polymodels#53]
Hi there!
Reading the following sentence:
> Subclass PolymorphicModel, an abstract model class.

One can mistakenly believe that this package uses Django's [Abstract base class](https://docs.djangoproject.com/en/3.0/topics/db/models/#abstract-base-classes) approach to inheritance, when in fact it uses [Multi-table inheritance](https://docs.djangoproject.com/en/3.0/topics/db/models/#multi-table-inheritance).

I think it's important to explicitly state in the readme that this package uses (or only supports) MTI to implement inheritance.

Thanks,
Simon.

**Comment by charettes** [comment]
`PolymorphicModel` is an `abstract` base class

https://github.com/charettes/django-polymodels/blob/5f40923fd255598131c0f1e48ef6a1f689dd016a/polymodels/models.py#L186-L193

And should be subclassed by your base concrete class in your inheritance tree. You're welcome to submit a PR that makes that distinction clearer but the way it's formulated right now makes sense to me.
