### ISSUE TITLE
Renaming polymodel migrations in django 1.8

### ISSUE THREAD

**Issue by therocode** [charettes/django-polymodels#7]
Hello!

i am using django-polymodels and I needed to rename a model which inherits from another model which inherits from PolymorphicModel.  I renamed the model and ran makemigrations which properly detected the rename and made RenameModel migrations. However, when executing this, I got a warning saying that the content type of my old name is stale and needs to be deleted. When answering 'yes' to that, all model instances are deleted by cascading.

As I am not using content types myself, I figured it is related to the models being a polymodel since django-polymodels uses content types. I tried to circumvent this in many ways, for example by creating a new model to copy over all data in a data migration and then deleting the old model, but I also ran into problems with polymodels in the django 1.8 migrations. When loading models like so:

CombinedProduct = apps.get_model("product", "CombinedProduct")

and creating instances like CombinedProduct.create(...) or CombinedProduct(), I get an error saying that content type id null constraint failed. So it seems impossible to create new instances of models based on polymodels through the method advised in migrations.

Are these issues just me, or are they issues in the polymodels library? If not, how do I do proper rename migrations with django-polymodels?

**Comment by charettes** [comment]
Hi @therocode,

Thanks for the report but this issue is not related to polymodels but to Django itself, see [#24067](https://code.djangoproject.com/ticket/24067).

**Comment by charettes** [comment]
Until the Django bug is fixed you should make sure to run a data migration that update the content type associated with your model from `OldName` to `NewName`.

e.g.

```
#!python
def rename_my_model_content_type(apps, schema_editor)
    content_types = apps.get_model('contenttypes.ContentType').objects
    assert content_types.filter(
        app_label='my_app', model='MyOldModelName'.lower()
    ).update(model='MyNewModelName'.lower()) == 1
```

**Comment by therocode** [comment]
Thanks for the reply!

Ah, typical that it would be a django bug hehe.

Thanks for your tip on how to fix it, however when I tried it I get "django.db.utils.IntegrityError: UNIQUE constraint failed: django_content_type.app_label, django_content_type.model". This is when I run it after the rename migration already occurred. 

Any ideas on how to work around that?

**Comment by therocode** [comment]
Oh, never mind, it worked after resetting the database. 

Thanks for your help!
