### ISSUE TITLE
m2m relation through a polymodel cannot use `string` definiton

### ISSUE THREAD

**Issue by chenull** [charettes/django-polymodels#9]
I am testing using django master and 1.8, and latest polymodels (1.2.3). The ``Organization`` model has a m2m relation to a polymodel based model ``Subscription``:

This won't work:
```
class Organization(models.Model)
    subscriptions = models.ManyToManyField('billing.Plan',
                                           related_name='subscribes',
                                           through='billing.Subscription')
```
Throwing error:
```
ERRORS:
organization.Organization.subscriptions: (fields.E331) Field specifies a many-to-many relation through model 'billing.Subscription', which has not been installed.
```

But when i changed to:
```
class Organization(models.Model)
    subscriptions = models.ManyToManyField('billing.Plan',
                                           related_name='subscribes',
                                           through=Subscription)
```
It works. makemigrations creates the schema migrations

Before the the ``Subscription`` using ``PolymorphicModel`` (i've used regular ``models.Model`` before), which as i can remember, didn't throw any error when either using 'string based' method when specifying m2m through, or the import method one

Thank you

**Comment by charettes** [comment]
Hi @chenull, I've tried to reproduce your reported issue with no success.

Is it possible that your `Subscription` model doesn't live in the same module as your `Plan` one?

What does `Subscription._meta.app_label` yields?
